export const ANGOS_USER_CURRENT = "ANGOS_USER_CURRENT";
export const ANGOS_PROJECT_LIST = "ANGOS_PROJECT_LIST";
export const ANGOS_PROJECT_CURRENT_ITEM = "ANGOS_PROJECT_CURRENT_ITEM";
export const ANGOS_FEATURE_LIST = "ANGOS_FEATURE_LIST";
export const ANGOS_FEATURE_CURRENT_ITEM = "ANGOS_FEATURE_CURRENT_ITEM";